# Generated by Django 5.0.1 on 2024-01-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_csi_member',
            field=models.BooleanField(default=False),
        ),
    ]
