# Generated by Django 5.0.1 on 2024-01-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_is_csi_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_csi_member',
        ),
    ]
